"""
Build a self-contained HTML page that renders MusicXML with OpenSheetMusicDisplay
and plays it back using real piano samples via soundfont-player + MusyngKite samples.
Falls back to Web Audio synthesis with reverb if samples can't be loaded.

Cursor + audio sync strategy:
  - buildSchedule() walks the OSMD cursor ONCE and records, per step, both the
    absolute score timestamp (currentTimeStamp.RealValue → seconds via tempoMap)
    AND the notes struck at that step (CurrentVoiceEntries → Notes → MIDI).
  - The audio is scheduled FROM that same list, so every cursor step and the sound
    for that step share a single timestamp — cursor, audio and the printed note are
    always the same event and cannot drift apart.  (An earlier version timed audio
    from a separate MusicXML parse; the two time-bases disagreed on OMR scores and
    the cursor ran ahead of the sound.)
  - The RAF loop advances the cursor each frame until the next step's timestamp
    passes the AUDIBLE clock position (songPos minus the audio output latency).
"""

import base64
import os
import urllib.request
import xml.etree.ElementTree as ET

# MusicXML namespace (some files include it, many don't)
_MXL_NS = "http://www.musicxml.org/ns/musicxml"

# Patched OSMD is cached next to this file so it's only downloaded once.
_OSMD_CACHE = os.path.join(os.path.dirname(__file__), "_osmd_patched.js")
_OSMD_CDN   = "https://cdn.jsdelivr.net/npm/opensheetmusicdisplay@1.9.4/build/opensheetmusicdisplay.min.js"
_OSMD_BUG   = "(t.sourceNote.Pitch?.getHalfTone()??0)-(e.sourceNote.Pitch.getHalfTone()??0)"
_OSMD_FIX   = "(t.sourceNote.Pitch?.getHalfTone()??0)-(e.sourceNote.Pitch?.getHalfTone()??0)"


def _get_osmd_js() -> str:
    """
    Return the patched OSMD JS.  Downloads and patches once; cached to disk.

    The patch adds an optional-chaining operator to the second comparand in
    GraphicalVoiceEntry.sortForVexflow — a one-character bug in OSMD 1.9.4 that
    causes 'Cannot read properties of undefined (reading getHalfTone)' when a
    voice entry contains a note with undefined Pitch (e.g. a rest in a chord
    context generated by HOMR OMR output).
    """
    # Return cached version if already patched
    if os.path.exists(_OSMD_CACHE):
        with open(_OSMD_CACHE, "r", encoding="utf-8") as f:
            return f.read()

    # Download from CDN
    try:
        with urllib.request.urlopen(_OSMD_CDN, timeout=30) as r:
            js = r.read().decode("utf-8")
    except Exception as exc:
        # On download failure, return empty string — caller falls back to CDN tag
        print(f"[sheet_viewer] OSMD download failed: {exc}")
        return ""

    # Apply the one-character fix
    patched = js.replace(_OSMD_BUG, _OSMD_FIX, 1)
    if patched == js:
        print("[sheet_viewer] WARNING: OSMD patch pattern not found — using unpatched JS")

    # Cache to disk
    try:
        with open(_OSMD_CACHE, "w", encoding="utf-8") as f:
            f.write(patched)
    except OSError:
        pass  # write failure is non-fatal

    return patched


def _sanitize_musicxml(xml_content: str) -> str:
    """
    Fix common issues in HOMR-generated MusicXML that crash OSMD's renderer.

    OSMD throws 'Cannot read properties of undefined (reading getHalfTone)'
    when it encounters notes whose pitch couldn't be parsed — e.g. notes with
    no <pitch> and no <rest>, unpitched percussion notes, or notes with an
    incomplete/invalid <pitch> element.

    This sanitiser removes or converts such notes before the XML reaches OSMD.
    """
    try:
        # Detect namespace prefix once
        ns = f"{{{_MXL_NS}}}" if f'xmlns="{_MXL_NS}"' in xml_content else ""

        root = ET.fromstring(xml_content)

        removed = 0
        for measure in root.iter(f"{ns}measure"):
            to_remove = []
            for note in list(measure.findall(f"{ns}note")):
                # Rests are always fine
                if note.find(f"{ns}rest") is not None:
                    continue

                unpitched = note.find(f"{ns}unpitched")
                pitch = note.find(f"{ns}pitch")

                # Unpitched percussion in a piano part → remove
                if unpitched is not None:
                    to_remove.append(note)
                    continue

                # No pitch, no rest → convert to rest so OSMD keeps the rhythm
                if pitch is None:
                    ET.SubElement(note, f"{ns}rest")
                    continue

                # Pitch element exists but is incomplete
                step = pitch.find(f"{ns}step")
                octave = pitch.find(f"{ns}octave")
                if (
                    step is None or octave is None
                    or not (step.text or "").strip()
                    or not (octave.text or "").strip()
                    or (step.text or "").strip() not in "CDEFGAB"
                ):
                    to_remove.append(note)
                    continue

                # Octave out of piano range → remove (OSMD can handle 0-9, HOMR
                # occasionally emits garbage octave values from misread beams)
                try:
                    if not (0 <= int(octave.text.strip()) <= 9):
                        to_remove.append(note)
                except ValueError:
                    to_remove.append(note)

            # Remove grace notes entirely — OSMD's sortForVexflow compares pitches
            # of all graphical notes in a measure via getHalfTone(), but grace notes
            # generated by HOMR don't carry a properly-initialised Pitch object after
            # OSMD's graphical pass, causing a crash.  Grace notes are ornamental and
            # skipping them does not affect playback or readability.
            for note in measure.findall(f"{ns}note"):
                if note.find(f"{ns}grace") is not None:
                    to_remove.append(note)

            # Strip empty <notations/> elements — these cause OSMD to iterate over
            # an empty list and can produce similar undefined-object errors.
            for note in measure.findall(f"{ns}note"):
                for notations in note.findall(f"{ns}notations"):
                    if len(notations) == 0:
                        note.remove(notations)
                        removed += 1

            for note in to_remove:
                try:
                    measure.remove(note)
                    removed += 1
                except ValueError:
                    pass

        if removed == 0:
            return xml_content  # nothing changed — return original string as-is

        result = ET.tostring(root, encoding="unicode")
        # Preserve any leading XML declaration
        stripped = xml_content.lstrip()
        if stripped.startswith("<?xml"):
            decl_end = xml_content.index("?>") + 2
            result = xml_content[: decl_end] + "\n" + result
        return result

    except Exception:
        return xml_content  # if anything goes wrong, pass through unchanged


def build_viewer_html(xml_content: str) -> str:
    # Remove malformed notes before OSMD sees them (prevents getHalfTone crash)
    xml_content = _sanitize_musicxml(xml_content)
    xml_b64 = base64.b64encode(xml_content.encode("utf-8")).decode("ascii")

    # Use locally-patched OSMD JS (one-char fix for sortForVexflow null check).
    # Fall back to CDN <script> tag if the download hasn't completed yet.
    osmd_js = _get_osmd_js()
    if osmd_js:
        osmd_tag = f"<script>{osmd_js}</script>"
    else:
        osmd_tag = '<script src="https://cdn.jsdelivr.net/npm/opensheetmusicdisplay@1.9.4/build/opensheetmusicdisplay.min.js"></script>'

    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ background: #fff; font-family: Inter, -apple-system, BlinkMacSystemFont, sans-serif; }}

    #toolbar {{
      position: sticky; top: 0; z-index: 100;
      display: flex; align-items: center; gap: 8px; flex-wrap: wrap;
      padding: 10px 14px;
      background: #f8fafc;
      border-bottom: 1px solid #e2e8f0;
    }}
    .btn {{
      display: inline-flex; align-items: center; gap: 4px;
      padding: 6px 14px; border-radius: 8px;
      border: 1.5px solid #e2e8f0; background: #fff;
      cursor: pointer; font-size: 13px; font-weight: 700;
      color: #111827; line-height: 1; white-space: nowrap;
      transition: border-color .15s, color .15s, transform .12s;
    }}
    .btn:hover:not(:disabled) {{ border-color: #14b8a6; color: #0f766e; transform: translateY(-1px); }}
    .btn.play  {{ background: #0f766e; color: #fff; border-color: #0f766e; }}
    .btn.play:hover:not(:disabled) {{ opacity: .88; transform: translateY(-1px); }}
    .btn:disabled {{ opacity: .38; cursor: default; pointer-events: none; }}
    .btn.active {{ background: #0f766e; color: #fff; border-color: #0f766e; }}

    .sep {{ width: 1px; height: 22px; background: #e2e8f0; flex-shrink: 0; }}
    #prog-wrap {{ flex: 1; display: flex; align-items: center; gap: 8px; min-width: 100px; }}
    #prog-bar {{ flex: 1; height: 5px; border-radius: 3px; background: #e2e8f0; overflow: hidden; }}
    #prog-fill {{ height: 100%; border-radius: 3px; background: #14b8a6; width: 0%; }}
    #time-lbl {{ font-size: 12px; color: #64748b; white-space: nowrap; min-width: 76px; text-align: right; }}
    #status {{ font-size: 12px; color: #94a3b8; white-space: nowrap; max-width: 260px; overflow: hidden; text-overflow: ellipsis; }}

    #sheet {{ padding: 16px 12px; }}
    #sheet svg {{ max-width: 100%; height: auto; }}
    #err {{
      display: none; margin: 16px; padding: 14px 16px; border-radius: 8px;
      background: #fef2f2; color: #dc2626; font-size: 13px; border: 1px solid #fecaca;
    }}
  </style>
</head>
<body>

<div id="toolbar">
  <button class="btn play" id="playBtn" disabled>▶ Play</button>
  <button class="btn" id="stopBtn" disabled>■ Stop</button>
  <div class="sep"></div>
  <button class="btn"        id="s50"  data-speed="0.5" >0.5×</button>
  <button class="btn"        id="s75"  data-speed="0.75">0.75×</button>
  <button class="btn active" id="s100" data-speed="1"   >1×</button>
  <button class="btn"        id="s125" data-speed="1.25">1.25×</button>
  <div class="sep"></div>
  <div id="prog-wrap">
    <div id="prog-bar"><div id="prog-fill"></div></div>
    <span id="time-lbl">0:00 / 0:00</span>
  </div>
  <span id="status">Loading…</span>
</div>

<div id="err"></div>
<div id="sheet"></div>

{osmd_tag}
<script src="https://cdn.jsdelivr.net/npm/soundfont-player@0.12.0/dist/soundfont-player.min.js"></script>
<script>
(function () {{

  // ── Decode XML ────────────────────────────────────────────────────────────────
  const XML_B64 = "{xml_b64}";
  function decodeXML() {{
    const bin = atob(XML_B64);
    const buf = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) buf[i] = bin.charCodeAt(i);
    return new TextDecoder('utf-8').decode(buf);
  }}

  // ── MusicXML parser ───────────────────────────────────────────────────────────
  // Returns: {{ notes, bpm, totalSec, tempoMap }}
  // tempoMap: [{{wholeNoteStart, secStart, bpm}}] — sorted by wholeNoteStart.
  // tempoMap is used by buildSchedule() to convert OSMD whole-note timestamps → seconds.
  // (notes[] is now only a fallback if OSMD yields no playable notes.)
  function parseMusicXML(xmlStr) {{
    const doc = new DOMParser().parseFromString(xmlStr, 'application/xml');
    let divisions = parseInt(doc.querySelector('divisions')?.textContent || '1', 10) || 1;
    let bpm = parseFloat(doc.querySelector('sound[tempo]')?.getAttribute('tempo') || '80') || 80;
    let spt = 60 / bpm / divisions;

    const notes    = [];
    const tempoMap = [{{ wholeStart: 0, secStart: 0, bpm }}]; // initial entry
    let globalTick = 0;   // ticks from piece start
    let globalSec  = 0;   // seconds from piece start (parallel to ticks)
    let globalWhole = 0;  // whole notes from piece start

    doc.querySelectorAll('measure').forEach(measure => {{
      let pos = globalTick, maxPos = globalTick, lastStart = globalTick;

      Array.from(measure.children).forEach(el => {{
        switch (el.tagName) {{
          case 'attributes': {{
            const d = el.querySelector('divisions');
            if (d) {{
              const prevDiv = divisions;
              divisions = parseInt(d.textContent, 10) || divisions;
              spt = 60 / bpm / divisions;
            }}
            break;
          }}
          case 'direction': {{
            const s = el.querySelector('sound[tempo]');
            if (s) {{
              const newBpm = parseFloat(s.getAttribute('tempo')) || bpm;
              if (Math.abs(newBpm - bpm) > 0.1) {{
                // Record tempo change: current pos in whole notes and seconds
                const changeWhole = globalWhole + (pos - globalTick) / (4 * divisions);
                const changeSec   = globalSec   + (pos - globalTick) * spt;
                bpm = newBpm;
                spt = 60 / bpm / divisions;
                tempoMap.push({{ wholeStart: changeWhole, secStart: changeSec, bpm }});
              }}
            }}
            break;
          }}
          case 'note': {{
            const isChord = !!el.querySelector('chord');
            const isRest  = !!el.querySelector('rest');
            const dur     = parseInt(el.querySelector('duration')?.textContent || '0', 10);
            const start   = isChord ? lastStart : pos;
            if (!isChord) {{ lastStart = pos; pos += dur; maxPos = Math.max(maxPos, pos); }}
            if (!isRest && dur > 0) {{
              const step   = el.querySelector('step')?.textContent;
              const octave = el.querySelector('octave')?.textContent;
              const alter  = parseFloat(el.querySelector('alter')?.textContent || '0');
              if (step && octave) {{
                const acc = alter === 1 ? '#' : alter === -1 ? 'b' : '';
                notes.push({{
                  time: globalSec + (start - globalTick) * spt,
                  note: step + acc + octave,
                  dur:  Math.max(0.06, dur * spt * 0.92),
                }});
              }}
            }}
            break;
          }}
          case 'backup': {{ pos -= parseInt(el.querySelector('duration')?.textContent || '0', 10); break; }}
          case 'forward': {{
            const d = parseInt(el.querySelector('duration')?.textContent || '0', 10);
            pos += d; maxPos = Math.max(maxPos, pos); break;
          }}
        }}
      }});

      // Advance global counters by this measure's duration
      const measureTicks = maxPos - globalTick;
      globalSec   += measureTicks * spt;
      globalWhole += measureTicks / (4 * divisions);
      globalTick   = maxPos;
    }});

    return {{ notes, bpm: tempoMap[0].bpm, totalSec: globalSec, tempoMap }};
  }}

  // Convert a whole-note position to seconds using the tempoMap
  function wholeToSec(whole, tempoMap) {{
    let seg = tempoMap[0];
    for (const s of tempoMap) {{
      if (s.wholeStart <= whole + 1e-9) seg = s;
      else break;
    }}
    return seg.secStart + (whole - seg.wholeStart) * (4 * 60 / seg.bpm);
  }}

  // ── Audio state ───────────────────────────────────────────────────────────────
  let audioCtx   = null;
  let piano      = null;
  let useSynth   = false;
  let reverbNode = null;

  // ── Synthesis fallback ─────────────────────────────────────────────────────────
  const BASE_FREQ = {{
    'C':261.63,'C#':277.18,'Db':277.18,'D':293.66,'D#':311.13,'Eb':311.13,
    'E':329.63,'F':349.23,'F#':369.99,'Gb':369.99,'G':392.00,'G#':415.30,
    'Ab':415.30,'A':440.00,'A#':466.16,'Bb':466.16,'B':493.88,
  }};
  function noteToFreq(name) {{
    const m = name.match(/^([A-G][#b]?)(-?\\d+)$/);
    if (!m) return null;
    const base = BASE_FREQ[m[1]];
    return base ? base * Math.pow(2, parseInt(m[2], 10) - 4) : null;
  }}
  function makeReverb(ctx) {{
    const len = Math.ceil(ctx.sampleRate * 2.2);
    const ir  = ctx.createBuffer(2, len, ctx.sampleRate);
    for (let c = 0; c < 2; c++) {{
      const ch = ir.getChannelData(c);
      for (let i = 0; i < len; i++) {{
        ch[i] = (Math.random() * 2 - 1) * Math.pow(1 - i / len, 3.5);
        if (i < 0.015 * ctx.sampleRate) ch[i] *= 1.6;
      }}
    }}
    const conv = ctx.createConvolver(); conv.buffer = ir; return conv;
  }}
  function synthNote(freq, when, duration) {{
    const ctx = audioCtx;
    const dry = ctx.createGain(); dry.gain.value = 0.72; dry.connect(ctx.destination);
    const wet = ctx.createGain(); wet.gain.value = 0.28;
    if (reverbNode) {{ wet.connect(reverbNode); reverbNode.connect(ctx.destination); }}
    else wet.connect(ctx.destination);
    const vol = Math.min(0.28, 0.026 * Math.sqrt(440 / Math.max(freq, 50)));
    const B = 0.00012;
    [[1,1.0],[2,0.55],[3,0.22],[4,0.12],[5,0.06],[6,0.03],[7,0.015],[8,0.007]].forEach(([n,amp]) => {{
      const f = freq * n * Math.sqrt(1 + B * n * n);
      if (f > 20000) return;
      const osc = ctx.createOscillator(); const g = ctx.createGain();
      osc.type = 'sine'; osc.frequency.value = f;
      const k = 0.5 + 0.5 * n;
      const pk = amp * vol;
      g.gain.setValueAtTime(0, when);
      g.gain.linearRampToValueAtTime(pk,       when + 0.004);
      g.gain.exponentialRampToValueAtTime(pk*0.45, when + 0.06*k);
      g.gain.exponentialRampToValueAtTime(pk*0.22, when + duration*0.55);
      g.gain.exponentialRampToValueAtTime(0.0001,  when + duration + 0.08/k);
      osc.connect(g); g.connect(dry); g.connect(wet);
      osc.start(when); osc.stop(when + duration + 0.18);
    }});
    const nb = ctx.createBuffer(1, Math.ceil(ctx.sampleRate*0.016), ctx.sampleRate);
    const nd = nb.getChannelData(0); for (let i=0;i<nd.length;i++) nd[i]=Math.random()*2-1;
    const ns=ctx.createBufferSource(); ns.buffer=nb;
    const bp=ctx.createBiquadFilter(); bp.type='bandpass'; bp.frequency.value=freq*2.8; bp.Q.value=2;
    const ng=ctx.createGain();
    ng.gain.setValueAtTime(0.055,when); ng.gain.exponentialRampToValueAtTime(0.0001,when+0.02);
    ns.connect(bp); bp.connect(ng); ng.connect(ctx.destination);
    ns.start(when); ns.stop(when+0.022);
  }}
  function playNote(noteName, when, duration) {{
    if (!useSynth && piano) {{
      try {{ piano.play(noteName, when, {{ duration, gain: 0.85 }}); }} catch (_) {{}}
    }} else {{
      const freq = noteToFreq(noteName);
      if (freq && freq > 20 && freq < 20000) synthNote(freq, when, duration);
    }}
  }}
  // Play by MIDI number — used by the OSMD-derived schedule (soundfont-player
  // accepts a MIDI number directly; the synth fallback converts to frequency).
  function playMidi(midi, when, duration) {{
    if (!useSynth && piano) {{
      try {{ piano.play(midi, when, {{ duration, gain: 0.85 }}); }} catch (_) {{}}
    }} else {{
      const freq = 440 * Math.pow(2, (midi - 69) / 12);
      if (freq > 20 && freq < 20000) synthNote(freq, when, duration);
    }}
  }}

  // ── Playback + cursor state ───────────────────────────────────────────────────
  let state          = 'idle';   // idle | playing | paused
  let scoreData      = null;
  let cursorTimesSec = [];       // score-seconds for each OSMD cursor step
  let playSchedule   = [];       // per-step: sec + the notes struck at that step.
                                 // ONE list shared by audio + cursor so they can
                                 // never drift apart.
  let cursorStep     = 0;
  let rafId          = null;
  let endTimer       = null;
  let speed          = 1.0;
  let playStartAt    = 0;        // audioCtx.currentTime at which song position 0 was
  let pausedPos      = 0;        // wall-clock seconds into the piece when paused

  const $         = id => document.getElementById(id);
  const setStatus = s  => $('status').textContent = s;
  const fmt       = s  => Math.floor(s/60) + ':' + String(Math.floor(s%60)).padStart(2,'0');

  function totalSecAtSpeed() {{ return (scoreData?.totalSec || 0) / speed; }}
  // Wall-clock seconds elapsed since play started
  function songPos() {{ return Math.max(0, audioCtx ? audioCtx.currentTime - playStartAt : pausedPos); }}
  // Seconds of audio actually AUDIBLE right now. audioCtx.currentTime is when a
  // note is *scheduled*; the sound leaves the speakers ~outputLatency later, so
  // the cursor must lag songPos() by that much to line up with what's heard.
  function audiblePos() {{
    const lat = audioCtx ? (audioCtx.outputLatency || audioCtx.baseLatency || 0) : 0;
    return Math.max(0, songPos() - lat);
  }}
  function updateUI() {{
    const now = songPos(), total = totalSecAtSpeed();
    $('time-lbl').textContent  = fmt(now) + ' / ' + fmt(total);
    $('prog-fill').style.width = (total > 0 ? Math.min(now/total,1)*100 : 0) + '%';
  }}

  // ── Build the shared play schedule (after OSMD + parser are both ready) ──
  // We walk the OSMD cursor ONCE.  At every step we read both:
  //   • the absolute score timestamp (currentTimeStamp.RealValue, whole notes)
  //   • the notes actually struck at that step (CurrentVoiceEntries → Notes)
  // and store them together in playSchedule[].  The audio is then scheduled FROM
  // this same list, so each cursor step and the sound for that step share one
  // timestamp — the cursor, the audio and the note on the sheet are always the
  // same event.  (Previously audio used a separate MusicXML parse and the two
  // time-bases disagreed on OMR scores, so the cursor ran ahead of the sound.)
  function buildSchedule() {{
    cursorTimesSec = [];
    playSchedule   = [];
    const iter = osmd.cursor.Iterator || osmd.cursor.iterator;
    if (!iter) {{ console.warn('[schedule] iterator not found — sync disabled'); return; }}

    const tempoMap = scoreData?.tempoMap || [{{ wholeStart: 0, secStart: 0, bpm: 80 }}];

    const MAX_STEPS = 6000;
    let prevSec = -1;
    try {{
      osmd.cursor.reset();
      while (!osmd.cursor.iterator.EndReached && playSchedule.length < MAX_STEPS) {{
        const it    = osmd.cursor.iterator;
        const ts    = it.currentTimeStamp;
        const whole = (ts && typeof ts.RealValue === 'number') ? ts.RealValue : 0;
        let sec     = wholeToSec(whole, tempoMap);
        // Clamp non-monotonic timestamps (e.g. repeat jumps) so we never walk
        // backwards in the forward-only audio timeline.
        if (sec < prevSec) sec = prevSec;

        const stepNotes = [];
        const ves = it.CurrentVoiceEntries || [];
        for (const ve of ves) {{
          const notes = (ve && ve.Notes) || [];
          for (const note of notes) {{
            try {{
              if (!note || note.isRest()) continue;
              // Skip tie continuations — the held note is already ringing.
              const tie = note.NoteTie;
              if (tie && tie.StartNote && tie.StartNote !== note) continue;
              const pitch = note.Pitch;
              if (!pitch) continue;
              const freq = pitch.Frequency;
              const midi = (freq && freq > 0)
                ? Math.round(69 + 12 * Math.log2(freq / 440))
                : (typeof pitch.getHalfTone === 'function' ? pitch.getHalfTone() + 12 : null);
              if (midi == null || midi < 21 || midi > 108) continue;   // piano range
              const lenWhole = (note.Length && typeof note.Length.RealValue === 'number')
                ? note.Length.RealValue : 0;
              const dur = Math.max(0.06, (wholeToSec(whole + lenWhole, tempoMap) - sec) * 0.92);
              stepNotes.push({{ midi, dur }});
            }} catch (_) {{}}
          }}
        }}

        cursorTimesSec.push(sec);
        playSchedule.push({{ sec, notes: stepNotes }});
        prevSec = sec;
        osmd.cursor.next();
      }}
    }} catch (e) {{
      console.warn('[schedule] walk error:', e);
      cursorTimesSec = []; playSchedule = [];
    }} finally {{
      try {{ osmd.cursor.reset(); }} catch (_) {{}}
    }}

    if (cursorTimesSec.length < 2) {{ cursorTimesSec = []; playSchedule = []; return; }}

    // Align the progress bar + auto-stop timer with the audio we actually play.
    let endSec = 0, noteCount = 0;
    for (const st of playSchedule) {{
      noteCount += st.notes.length;
      for (const n of st.notes) endSec = Math.max(endSec, st.sec + n.dur);
    }}
    if (scoreData) {{
      if (endSec > 0) scoreData.totalSec = endSec;
      scoreData.noteCount = noteCount;
    }}
    console.log('[schedule] built', playSchedule.length, 'steps,', noteCount,
                'notes, end', endSec.toFixed(2), 's (shared timestamp base)');
  }}

  // ── Core play/pause/stop ──────────────────────────────────────────────────────
  async function doPlay(fromWallClock) {{
    const haveSchedule = playSchedule.length > 0;
    if (!haveSchedule && !scoreData?.notes?.length) {{ setStatus('No notes found'); return; }}
    if (audioCtx.state === 'suspended') await audioCtx.resume();

    // Schedule audio
    const startAt = audioCtx.currentTime + 0.08;
    playStartAt   = startAt - fromWallClock;

    if (haveSchedule) {{
      // Same list the cursor walks → audio and cursor cannot drift apart.
      playSchedule.forEach(st => {{
        const wallT = st.sec / speed;          // wall-clock time of this step
        if (wallT < fromWallClock - 0.04) return;
        const when = startAt + (wallT - fromWallClock);
        if (when < audioCtx.currentTime) return;
        st.notes.forEach(n => playMidi(n.midi, when, n.dur / speed));
      }});
    }} else {{
      // Fallback: OSMD gave us no playable notes — use the raw MusicXML parse.
      scoreData.notes.forEach(n => {{
        const wallT = n.time / speed;
        if (wallT < fromWallClock - 0.04) return;
        const when = startAt + (wallT - fromWallClock);
        if (when >= audioCtx.currentTime) playNote(n.note, when, n.dur / speed);
      }});
    }}

    // Auto-stop timer
    clearTimeout(endTimer);
    endTimer = setTimeout(() => {{ if (state === 'playing') doStop(); }},
                          (totalSecAtSpeed() - fromWallClock + 0.5) * 1000);

    state = 'playing';
    $('playBtn').textContent = '⏸ Pause';
    $('stopBtn').disabled    = false;
    rafLoop(); // drives progress bar + cursor
  }}

  function doPause() {{
    pausedPos = songPos();
    cancelAnimationFrame(rafId);
    clearTimeout(endTimer);
    if (piano) piano.stop();
    state = 'paused';
    $('playBtn').textContent = '▶ Play';
  }}

  function doStop() {{
    cancelAnimationFrame(rafId);
    clearTimeout(endTimer);
    if (piano) piano.stop();
    state    = 'idle';
    pausedPos = 0;
    osmd.cursor.reset();
    cursorStep = 0;
    updateUI();
    $('playBtn').textContent = '▶ Play';
    $('stopBtn').disabled    = true;
  }}

  // RAF: updates progress bar + drives cursor from the live audio clock.
  // The cursor step is advanced whenever the AUDIBLE position passes the next
  // step's real score-time (read from each step's OSMD timestamp).
  function rafLoop() {{
    if (state !== 'playing') return;
    updateUI();
    if (cursorTimesSec.length > 1) {{
      const scoreSec = audiblePos() * speed;
      while (cursorStep < cursorTimesSec.length - 1 &&
             cursorTimesSec[cursorStep + 1] <= scoreSec) {{
        osmd.cursor.next();
        cursorStep++;
      }}
    }}
    rafId = requestAnimationFrame(rafLoop);
  }}

  // ── OSMD init ─────────────────────────────────────────────────────────────────
  // Declare sheetLoaded here (before any error handlers that reference it)
  let sheetLoaded = false;

  const osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay('sheet', {{
    autoResize: true, drawTitle: true, followCursor: true,
    cursorOptions: [{{ type: 0, color: '#14b8a6', alpha: 0.45, follow: true }}],
  }});

  const xmlStr = decodeXML();

  function onOsmdLoaded() {{
    // osmd.load() only builds the graphical model; render() must be called explicitly
    // to paint the SVG to the DOM and allow the cursor to position itself correctly.
    try {{ osmd.render(); }}
    catch (renderErr) {{
      console.warn('[OSMD] render error:', renderErr);
      // Non-fatal: autoResize may still trigger a render, so continue.
    }}

    // Parse score (fast — pure JS, no DOM)
    try {{ scoreData = parseMusicXML(xmlStr); }}
    catch (e) {{
      console.warn('parseMusicXML error:', e);
      scoreData = {{ notes:[], bpm:80, totalSec:0,
                     tempoMap:[{{wholeStart:0,secStart:0,bpm:80}}] }};
    }}

    sheetLoaded = true;
    if (audioCtx) $('playBtn').disabled = false;

    // Defer cursor build one frame so the SVG layout is fully committed to the DOM
    // before we call cursor.show() (which calls update() to measure cursor position).
    setTimeout(() => {{
      try {{
        osmd.cursor.hide();
        buildSchedule();
        osmd.cursor.reset();
        osmd.cursor.show();
      }} catch (e) {{
        console.warn('cursor build error:', e);
        try {{ osmd.cursor.show(); }} catch (_) {{}}
      }}
      tryEnablePlay();
    }}, 50);
  }}

  function onOsmdError(err) {{
    console.error('[OSMD] error:', err);
    $('err').style.display = 'block';
    $('err').textContent   = 'Failed to load sheet: ' + (err?.message || String(err));
    setStatus('Error loading sheet');
  }}

  // osmd.load() is marked async but can still throw synchronously before the
  // Promise is returned (OSMD calls new GraphicalMusicSheet() synchronously).
  // Wrap the entire call to catch both paths.
  let loadPromise = null;
  try {{
    loadPromise = osmd.load(xmlStr);
  }} catch (syncErr) {{
    onOsmdError(syncErr);
  }}

  if (loadPromise) {{
    loadPromise.then(onOsmdLoaded).catch(onOsmdError);
  }}

  // ── Audio init ─────────────────────────────────────────────────────────────────

  function tryEnablePlay() {{
    sheetLoaded = true;
    if (audioCtx) {{
      $('playBtn').disabled = false;
      const label = scoreData ? ' · ' + Math.round(scoreData.bpm) + ' BPM' : '';
      // status already set by initAudio, just add note count
      const noteCount = scoreData?.noteCount ?? scoreData?.notes?.length ?? 0;
      setStatus((useSynth ? 'Synth mode' : '🎹 Piano loaded') + ' · ' + noteCount + ' notes' + label);
    }}
  }}

  function initAudio() {{
    if (audioCtx) return; // already created
    audioCtx   = new (window.AudioContext || window.webkitAudioContext)();
    reverbNode = makeReverb(audioCtx);
    setStatus('Loading piano samples…');

    Soundfont.instrument(audioCtx, 'acoustic_grand_piano', {{
      soundfont: 'MusyngKite', format: 'mp3', gain: 5,
    }}).then(instr => {{
      piano    = instr;
      useSynth = false;
      if (sheetLoaded) tryEnablePlay();
      else setStatus('🎹 Piano loaded');
    }}).catch(() => {{
      useSynth = true;
      if (sheetLoaded) tryEnablePlay();
      else setStatus('Synth mode (samples unavailable)');
    }});

    if (sheetLoaded) $('playBtn').disabled = false; // allow click even while loading
  }}

  // ── Button handlers ───────────────────────────────────────────────────────────
  $('playBtn').addEventListener('click', async () => {{
    if (!audioCtx) initAudio();
    if (!audioCtx || !scoreData) return;

    if (state === 'idle')    await doPlay(0);
    else if (state === 'playing') doPause();
    else if (state === 'paused')  await doPlay(pausedPos);
  }});

  $('stopBtn').addEventListener('click', doStop);

  // ── Speed buttons ─────────────────────────────────────────────────────────────
  document.querySelectorAll('.btn[data-speed]').forEach(btn => {{
    btn.addEventListener('click', async () => {{
      const wasPlaying  = state === 'playing';
      const scorePosNow = songPos() * speed;  // current score-seconds

      // Stop current playback cleanly
      cancelAnimationFrame(rafId);
      clearTimeout(endTimer);
      if (piano) piano.stop();
      state = 'idle';

      // Update speed
      speed     = parseFloat(btn.dataset.speed);
      pausedPos = scorePosNow / speed;       // new wall-clock position

      // Re-position cursor to the score position that matches scorePosNow
      osmd.cursor.reset();
      cursorStep = 0;
      for (let s = 1; s < cursorTimesSec.length; s++) {{
        if (cursorTimesSec[s] <= scorePosNow) {{ osmd.cursor.next(); cursorStep = s; }}
        else break;
      }}
      updateUI();

      // Highlight active speed button
      document.querySelectorAll('.btn[data-speed]').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');

      if (wasPlaying && audioCtx) {{
        await doPlay(pausedPos);
      }} else {{
        $('playBtn').textContent = '▶ Play';
      }}
    }});
  }});

  // Pre-load audio in background as soon as page is interactive
  document.addEventListener('DOMContentLoaded', initAudio);

}})();
</script>
</body>
</html>"""
